kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  PGADMIN_CONFIG_SERVER_MODE: "True"
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2', 'internal']"
