apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-vault
    create: true
    overwrite: true
    transformation:
      templates:
        PGADMIN_DEFAULT_EMAIL:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "defaultEmail") {{ "-}}" }}
        PGADMIN_DEFAULT_PASSWORD:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "defaultPassword") {{ "-}}" }}
        PGADMIN_CONFIG_OAUTH2_CONFIG:
          text: |
            [{
              "OAUTH2_NAME": "authentik",
              "OAUTH2_DISPLAY_NAME": "Authentik",
              "OAUTH2_CLIENT_ID": {{ "{{" }} printf "%q" (get .Secrets "authentikClientId") {{ "}}" }},
              "OAUTH2_CLIENT_SECRET": {{ "{{" }} printf "%q" (get .Secrets "authentikClientSecret") {{ "}}" }},
              "OAUTH2_SERVER_METADATA_URL": "https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/pgadmin/.well-known/openid-configuration",
              "OAUTH2_SCOPE": "openid email profile",
              "OAUTH2_AUTO_CREATE_USER": True,
              "OAUTH2_CHALLENGE_METHOD": "S256",
              "OAUTH2_RESPONSE_TYPE": "code"
            }]
