vaultDataPath: /srv/appdata/core-services/vault/data

backup:
  enabled: true
  resticImage: restic/restic:0.19.1
  rcloneImage: rclone/rclone:1.74.4

vault:
  global:
    namespace: core-services
  injector:
    enabled: true
  server:
    logLevel: debug
    enabled: true
    dataStorage:
      storageClass: manual
  ui:
    enabled: true
    serviceType: "LoadBalancer"
