image: dpage/pgadmin4:9.16
namespace: core-services

host:
  subdomain: pgadmin

secrets:
  domain:
    key: homeDomain
    path: kv/data/domains

ports:
- name: pgadmin4
  containerPort: 80
  externalPort: 5050
  protocol: TCP

volumes:
- name: config
  hostPath: /srv/appdata/core-services/pgadmin/data
  podPath: /var/lib/pgadmin
  type: DirectoryOrCreate
