apiVersion: networking.alm.homelab/v1
kind: CertificateRequest
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-certificate-secret
  commonName: {{ .Values.host.subdomain }}
  domainKey: {{ .Values.secrets.homeDomain.key }}
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  vaultPath: {{ .Values.secrets.homeDomain.path }}
