apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.crowdsec.namespaceOverride | default "core-services" }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.crowdsec.namespaceOverride | default "core-services" }}
  mount: kv
  type: kv-v2
  path: core-services/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}-web-ui-oidc
  namespace: {{ .Values.crowdsec.namespaceOverride | default "core-services" }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.crowdsec.namespaceOverride | default "core-services" }}
  mount: kv
  type: kv-v2
  path: core-services/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-web-ui-oidc
    create: true
    overwrite: true
    transformation:
      templates:
        CROWDSEC_AUTH_OIDC_ISSUER_URL:
          text: |-
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/crowdsec/
        CROWDSEC_AUTH_OIDC_CLIENT_ID:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientId") {{ "-}}" }}
        CROWDSEC_AUTH_OIDC_CLIENT_SECRET:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientSecret") {{ "-}}" }}
