kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  PGID: '1000'
  PUID: '1000'
  ORIGIN: {{ .Values.origin | quote }}
  TZ: 'Europe/Bucharest'
