apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-vault
    create: true
    overwrite: true
    transformation:
      templates:
        OIDC_CLIENT_SECRET:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientSecret") {{ "-}}" }}
        OIDC_CLIENT_ID:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientId") {{ "-}}" }}
        OIDC_DISCOVERY_URL:
          text: |-
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/profilarr/.well-known/openid-configuration
