apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      volumes:
      - name: {{ .Release.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: code
        hostPath:
          path: /code
          type: DirectoryOrCreate
      - name: install-scripts
        configMap:
          name: {{ .Release.Name }}-install-scripts
          defaultMode: 0555
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        {{ if .Values.securityContext.enabled }}
        securityContext:
          privileged: {{ .Values.securityContext.privileged }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
          capabilities:
            add:
            {{ range .Values.securityContext.capabilities.add }}
            - {{ . }}
            {{ end }}
        {{ end }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        ports:
        {{- range $key, $val := $.Values.service.ports }}
        - containerPort: {{ $val.containerPort }}
          name: {{ $val.name }}
          protocol: {{ $val.protocol }}
        {{ end }}
        volumeMounts:
        {{- range $index, $val := $.Values.storage.volumes }}
        - mountPath: {{ $val.podPath }}
          name: {{ $.Release.Name }}
          subPath: {{ $val.subPath }}
        {{ end -}}
        - mountPath: /config/workspace
          name: code
        - mountPath: /custom-cont-init.d/05-clean-bwrap-filecap
          name: install-scripts
          subPath: 05-clean-bwrap-filecap
        - mountPath: /custom-cont-init.d/06-enable-vscode-global-navigator
          name: install-scripts
          subPath: 06-enable-vscode-global-navigator
        - mountPath: /custom-cont-init.d/10-install-helm
          name: install-scripts
          subPath: 10-install-helm
        - mountPath: /custom-cont-init.d/20-install-kubectl
          name: install-scripts
          subPath: 20-install-kubectl
        startupProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
