image: linuxserver/plex:1.43.0@sha256:84f8646e799f6636876ab4f283d9fc8f6c51d56098ea74cba82bfb85074b68df
namespace: media-management

host:
  subdomain: plex

secrets:
  primaryDomain:
    key: primaryDomain
    path: kv/data/domains
  homeDomain:
    key: homeDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/media-management/plex
  volumes:
  - name: config
    subPath: config
    podPath: /config
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 32400
    externalPort: 32400
    protocol: TCP