image: linuxserver/plex:1.43.1@sha256:e5c7c283b242966416a4bed2d666acf6f3fb8f957c704be8333f8dc987364825
namespace: media-management

host:
  subdomain: plex

secrets:
  primaryDomain:
    key: primaryDomain
    path: kv/data/domains
  homeDomain:
    key: homeDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/media-management/plex
  volumes:
  - name: config
    subPath: config
    podPath: /config
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 32400
    externalPort: 32400
    protocol: TCP