image: linuxserver/plex:1.43.3@sha256:7f9a1d574958fc2f177c14ca190d4b811a58c274477f5bae8fb44ee676fb96bf
namespace: media-management

host:
  subdomain: plex

secrets:
  primaryDomain:
    key: primaryDomain
    path: kv/data/domains
  homeDomain:
    key: homeDomain
    path: kv/data/domains

storage:
  appdataBasePath: /srv/appdata/media-management/plex
  volumes:
  - name: config
    subPath: config
    podPath: /config
    type: DirectoryOrCreate
    readOnly: false

service:
  type: ClusterIP
  ports:
  - name: http
    containerPort: 32400
    externalPort: 32400
    protocol: TCP