apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      volumes:
      - name: {{ .Release.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: media
        hostPath:
          path: /mnt/hdd
          type: Directory
      - name: backup
        hostPath:
          path: /mnt/hdd2
          type: Directory
      - name: hdd12tb
        hostPath:
          path: /mnt/hdd12tb
          type: Directory
      - name: services
        configMap:
          name: {{ .Release.Name }}-services
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        env:
        - name: HOMEPAGE_ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_ARGOCD_TOKEN
        - name: HOMEPAGE_AUTHENTIK_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_AUTHENTIK_TOKEN
        - name: HOMEPAGE_AUTOBRR_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_AUTOBRR_API_KEY
        - name: HOMEPAGE_BAZARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_BAZARR_API_KEY
        - name: HOMEPAGE_IMMICH_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_IMMICH_API_KEY
        - name: HOMEPAGE_JELLYFIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_JELLYFIN_API_KEY
        - name: HOMEPAGE_PLEX_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_PLEX_TOKEN
        - name: HOMEPAGE_QBITTORRENT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_QBITTORRENT_USERNAME
        - name: HOMEPAGE_QBITTORRENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_QBITTORRENT_PASSWORD
        - name: HOMEPAGE_RADARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_RADARR_API_KEY
        - name: HOMEPAGE_SEERR_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_SEERR_API_KEY
        - name: HOMEPAGE_SONARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_SONARR_API_KEY
        - name: HOMEPAGE_TAUTULLI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_TAUTULLI_API_KEY
        - name: HOMEPAGE_PAPERLESS_NGX_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_PAPERLESS_NGX_API_KEY
        - name: HOMEPAGE_PORTAINER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_PORTAINER_API_KEY
        - name: HOMEPAGE_MINIPC_PORTAINER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_MINIPC_PORTAINER_API_KEY
        - name: HOMEPAGE_HOME_ASSISTANT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_HOME_ASSISTANT_TOKEN
        - name: HOMEPAGE_OMADA_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_OMADA_USERNAME
        - name: HOMEPAGE_OMADA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_OMADA_PASSWORD
        - name: HOMEPAGE_TECHNITIUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: HOMEPAGE_TECHNITIUM_API_KEY
        - name: HOMEPAGE_PRIMARY_DOMAIN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-domains
              key: HOMEPAGE_PRIMARY_DOMAIN
        ports:
        {{- range $key, $val := $.Values.service.ports }}
        - containerPort: {{ $val.containerPort }}
          name: {{ $val.name }}
          protocol: {{ $val.protocol }}
        {{- end }}
        volumeMounts:
        {{- range $index, $val := $.Values.storage.volumes }}
        - mountPath: {{ $val.podPath }}
          name: {{ $.Release.Name }}
          subPath: {{ $val.subPath }}
        {{ end -}}
        - mountPath: /media
          name: media
          readOnly: true
        - mountPath: /backup
          name: backup
          readOnly: true
        - mountPath: /hdd12tb
          name: hdd12tb
          readOnly: true
        - mountPath: /app/config/services.yaml
          name: services
          subPath: services.yaml
          readOnly: true
