apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-secrets
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}-domains
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: domains
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-domains
    create: true
    overwrite: true
    transformation:
      templates:
        HOMEPAGE_VAR_PRIMARY_DOMAIN:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "primaryDomain") {{ "-}}" }}
