kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  # Chromadb configuration
  CHROMADB_HOST: "{{ .Values.chromadb.service }}.{{ .Values.chromadb.namespace }}.svc"
  CHROMADB_PORT: "{{ .Values.chromadb.port }}"
  
  # SearXNG for research/web search
  SEARXNG_INSTANCE: "http://{{ .Values.searxng.service }}.{{ .Values.searxng.namespace }}.svc:{{ .Values.searxng.port }}"
  
  # Ollama and other local models discovery
  LLM_HOST: "http://ollama.ai-services.svc:11434"
