apiVersion: v2
name: grafana
version: 1.0.0
dependencies:
- name: grafana
  version: 8.11.0
  repository: https://grafana.github.io/helm-charts
- name: loki
  version: 6.29.0
  repository: https://grafana.github.io/helm-charts
- name: alloy
  version: 0.12.5
  repository: https://grafana.github.io/helm-charts
