apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-vault
    create: true
    overwrite: true
    transformation:
      templates:
        GF_SERVER_ROOT_URL:
          text: |
            https://{{ .Values.host.subdomain }}.{{ "{{-" }} printf "%s" (get .Secrets "localDomain") {{ "-}}" }}
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientId") {{ "-}}" }}
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          text: |
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientSecret") {{ "-}}" }}
        GF_AUTH_GENERIC_OAUTH_AUTH_URL:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/authorize/
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/token/
        GF_AUTH_GENERIC_OAUTH_API_URL:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/userinfo/
        GF_AUTH_GENERIC_OAUTH_JWK_SET_URL:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/grafana/jwks/
        GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL:
          text: |
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/grafana/end-session/
