services:
  vmagent:
    image: victoriametrics/vmagent:v1.109.1
    container_name: vmagent
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
    command:
      - -promscrape.config=/etc/vmagent/config.yml
      - -remoteWrite.url=https://metrics.${HOME_DOMAIN}/api/v1/write
      - -remoteWrite.tlsInsecureSkipVerify=true
    volumes:
      - /srv/appdata/vmagent/config.yml:/etc/vmagent/config.yml:ro
      - /srv/appdata/vmagent/data:/vmagentdata
    networks:
      - monitoring
      - essentials_homeserver
    dns:
      - 172.17.0.1
    depends_on:
      - cadvisor
      - node-exporter

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.9.0
    container_name: node-exporter
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

  scrutiny-collector:
    image: ghcr.io/analogj/scrutiny:v0.8.6-collector
    container_name: scrutiny-collector
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
      - COLLECTOR_API_ENDPOINT=https://scrutiny.${HOME_DOMAIN}
      - COLLECTOR_HOST_ID=minipc
      - COLLECTOR_CRON_SCHEDULE=0 0 * * *
    volumes:
      - /run/udev:/run/udev:ro
    networks:
      - monitoring
      - essentials_homeserver
    dns:
      - 172.17.0.1
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
      - /dev/nvme0n1:/dev/nvme0n1

  iperf3:
    image: mlabbe/iperf3:latest
    container_name: iperf3
    restart: unless-stopped
    command: -s
    ports:
      - "5201:5201/tcp"
      - "5201:5201/udp"
    networks:
      - monitoring

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:3.2.14
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    read_only: true
    tmpfs:
      - /run

networks:
  monitoring:
    driver: bridge
  essentials_homeserver:
    external: true
