kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  server.yml: |
    base-url: "{{ .Values.ntfy.baseUrl }}"
    listen-http: "{{ .Values.ntfy.listenHttp }}"
    cache-file: "{{ .Values.ntfy.cacheFile }}"
    attachment-cache-dir: "{{ .Values.ntfy.attachmentCacheDir }}"
    behind-proxy: {{ .Values.ntfy.behindProxy }}
