apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.api.port }}
    targetPort: api
    name: api
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $val := $.Values.service.ports }}
  - port: {{ $val.externalPort }}
    targetPort: {{ $val.name }}
    name: {{ $val.name }}
    protocol: {{ $val.protocol }}
  {{ end -}}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: web
