apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}-domains
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ trimPrefix "kv/data/" .Values.secrets.domain.path }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}-api
  destination:
    name: {{ .Release.Name }}-domains
    create: true
    overwrite: true
    transformation:
      templates:
        ORIGIN:
          text: |-
            https://{{ .Values.host.subdomain }}.{{ "{{-" }} printf "%s" (get .Secrets "{{ .Values.secrets.domain.key }}") {{ "-}}" }}
        RP_ID:
          text: |-
            {{ .Values.host.subdomain }}.{{ "{{-" }} printf "%s" (get .Secrets "{{ .Values.secrets.domain.key }}") {{ "-}}" }}
