apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  HERMES_DASHBOARD: "1"
  HERMES_DASHBOARD_PUBLIC_URL: "https://{{ .Values.host.subdomain }}.home"
