apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .externalPort }}
      targetPort: {{ .name }}
      name: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
