image: itzg/minecraft-server:2026.7.0
namespace: game-servers

backup:
  enabled: true
  resticImage: restic/restic:0.19.1
  rcloneImage: rclone/rclone:1.74.3

ports:
- name: minecraft
  containerPort: 25565
  externalPort: 25565
  protocol: TCP

storage:
  appdataBasePath: /srv/appdata
  volumes:
  - name: data
    subPath: data
    podPath: /data
    type: DirectoryOrCreate