kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  openclaw.json: |
    {
      "agent": {
        "model": {{ .Values.ollama.model | quote }}
      },
      "gateway": {
        "bind": "lan",
        "port": 18789
      }
    }
