kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  openclaw.json: |
    {
      "agents": {
        "defaults": {
          "model": {
            "primary": {{ .Values.ollama.model | quote }}
          }
        }
      },
      "gateway": {
        "bind": "lan",
        "port": 18789,
        "controlUi": {
          "allowedOrigins": [
            "http://localhost:18789",
            "http://127.0.0.1:18789"
          ]
        }
      }
    }
