apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: vaultauth-{{ .Values.namespace }}
  mount: kv
  type: kv-v2
  path: {{ .Values.namespace }}/{{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}-vault
    create: true
    overwrite: true
    transformation:
      templates:
        QUI__OIDC_ISSUER:
          text: |-
            https://auth.{{ "{{-" }} printf "%s" (get .Secrets "authentikDomain") {{ "-}}" }}/application/o/qui/
        QUI__OIDC_CLIENT_ID:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientId") {{ "-}}" }}
        QUI__OIDC_CLIENT_SECRET:
          text: |-
            {{ "{{-" }} printf "%s" (get .Secrets "authentikClientSecret") {{ "-}}" }}
        QUI__OIDC_REDIRECT_URL:
          text: |-
            https://{{ .Values.host.subdomain }}.{{ "{{-" }} printf "%s" (get .Secrets "localDomain") {{ "-}}" }}/api/auth/oidc/callback
